### ISSUE TITLE
Vibrato Bug when exporting to midi.

### ISSUE THREAD

**Issue by Fujosej** [kuma4649/MDPlayer#42]
Hi , i really love your work with MDplayer , very handy tool.
I found some bugs with midi export. If you could look into them and maybe provide some kind of a fix , that would be really nice.
This is the options i use for export , i tried without vopmexe option. It has no effect on a bug.
https://ibb.co/D9gWRBf

Ok so here are the bugs , below are two Examples of Vibrato bug.In the video I show the original track using foobar to show what i mean.
https://streamable.com/rd3wj
https://streamable.com/roled

And here is a another bug 
https://streamable.com/2z4qp

And lastly , if its possible is there a way to save the instrument via VOPMex , cause midi CC really does a good job, would be amazing if i could import setting in VOPMex and save as an instrument for later use. As of right now its doing nothing.

**Comment by knight-ryu12** [comment]
For sure, You can export instrument by right clicking each channel "meta info" section.

**Comment by kuma4649** [comment]
こんにちは！MDPlayerを使っていただきありがとうございます。

さて、ご指摘の件、
ビブラートの個所がノートが分離してしまうということだとおもいます。
この原因は今のところMDPlayerの仕様ということになります。

ノートのビブラートが深いとMDPlayerは他のノートが鳴っていると判定してしまいます。
よって、動画のような演奏になっていると思われます。

考えられる対策としては、ノートの判定範囲を狭めてビブラートが深くても
音階が変わらないとMDPlayerに思わせるということになります。
しかしあまり狭めすぎるとそもそもノートが出ないというような症状も
発生することになります。

あまり効果的な対応にはならないのですが判定範囲を調整できるような設定を
一応用意してみようと思います。
対応に時間がかかると思いますので、
それまでは申し訳ありませんが手動での対応お願いします。

**Comment by knight-ryu12** [comment]
TR->Eng
Hello! Thanks for using MDPlayer.
So, the bug (I think) that vibrato is offing the note.
The problem is, that this is the spec of MDPlayer.

If Vibrato notes are too deep, MDPlayer thinks that notes are playing different.
Therefore, result is like you shown in the video.

The fix is, to decrease the threshold (or Judgement) between the note, So let MDPlayer thinks that this is not a different octave notes.
But decreasing the threshold maybe make note to disappear.

I'll prepare the settings that let you change the threshold.
This'll take some time, so please do it manually while I work for issue.

Sorry for inconvinience.

**Comment by Fujosej** [comment]
Thank you for answering me guys. That threshold setting would be a nice addition.

> For sure, You can export instrument by right clicking each channel "meta info" section.

I dont really understand what you mean here, right click where?

Can i do it in Reaper somehow? Export each instrument via VOPMex.

Each channel has this Midi CC info.
https://ibb.co/jfh9mSK

**Comment by kuma4649** [comment]
TAG140にて対応させていただきました。
キーオン後にFNUMを設定するタイプのドライバが使われているデータなどは逆効果の場合もあります。

**Comment by Fujosej** [comment]
Thank you very much , it works perfectly now.
